### ISSUE TITLE
Digits over Five aren’t vibrating correctly

### ISSUE THREAD

**Issue by kwang4** [Burrit0z/BuzzTime#2]
All digits above five have a huge pause to them instead of a long vibration.(I don’t know what long vibrations feel like). For example, 6:59 only does : one vibration and a long pause, another long pause, and four vibrations, probably part of nine. 
Also single digits like 7 only have 2 vibrations.

**Comment by Burrit0z** [comment]
May I ask what device and iOS you have?

**Comment by kwang4** [comment]
iOS 13.2.3 iPhone X

**Comment by kwang4** [comment]
Ok so apparently the long vibrations don't work if ringer is turned off. Can this restriction be bypassed?

**Comment by Burrit0z** [comment]
I can try to look into it, I’m really not sure. Unfortunately, my iPhone XR just lost its jb, and now I’m on 13.3. I’ll see what I can do.
